# -*- coding: utf-8 -*-
"""Aristocratas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qQxlkb6pDlJZ32My2BCutGxiQ5MsoEUH
"""

pip install yfinance

import pandas as pd
import yfinance as yf

"""##Descarga de tabla con empresas aristócratas"""

# UTILIZAMOS WEBSCRAP CON PANDAS, BUSCANDO TABLAS
ej = pd.read_html("https://en.wikipedia.org/wiki/S%26P_500_Dividend_Aristocrats")[0]

ej.info()

"""####Consulta del nombre de las columnas y el tipo de valores"""

ej.columns
ej.dtypes

ej.head()

ej[ej['Ticker symbol']=='BF.B']

ej['Ticker symbol'] = ej['Ticker symbol'].replace('BF.B', 'BF-B')

# VER VALORES ÚNICOS PARA COLUMNAS ESPECÍFICAS:
sectores = list(set(ej['Sector']))
empresas = list(set(ej['Company']))

sectores

len(empresas)

"""##Descarga de SP500"""

ej2 = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")[0]

ej2.info()

ej2[ej2['Symbol']=='BF.B']

ej2['Symbol'] = ej2['Symbol'].replace('BF.B', 'BF-B')

"""####Renombre de algunas columnas o variables"""

ej2 = ej2.rename(columns={'Symbol': 'Ticker symbol', 'GICS Sub-Industry': 'Industry'})

"""##Unión de las dos tablas a través del *ticker* de las empresas"""

ej_def = pd.merge(ej, ej2, how="inner",on='Ticker symbol')

ej_def.info()

ej_def.head(35)

"""##Otra unión: solo variables sector e industria; el *ticker* es el índice"""

aristocrats = ej2[['Ticker symbol', 'GICS Sector','Industry']][ej2['Ticker symbol'].isin(ej['Ticker symbol'])].set_index("Ticker symbol")

aristocrats.head()

aristocrats = aristocrats.replace('BF.B', 'BF-B')

"""###Creación de *dataframe* con la capitalización bursátil de las empresas *aristócratas*"""

df = yf.download(list(aristocrats.index), '2020-01-01', '2023-01-01')[['Open', 'Volume']]

mkap = df['Open']*df['Volume']

mkap.info()

mkap.head(70)